export const titles = [
  "The Mythical Man-Month",
  "Soft Skills: The Software Developer’s Life Manual",
  "schoolbag for puddle",
  "shocking for hurl precipitate",
  "memorialise remind harridan complain of",
  "nightie in kalotermes",
  "fantastical out proved",
  "purposefully devaluate decline jump with travel fly",
  "Refactoring: Improving the Design of Existing Code",
  "conceivability possible latent",
  "Out of Africa",
  "Learn Python the hard way",
  "flavor obvious demonstrable",
  "West with the Night",
  "The Flame Trees of Thika: Memories of an African Childhood",
  "The Constant Gardener",
  "Born Free: A Lioness of Two Worlds (Story of Elsa, #1)",
  "White Mischief",
  "Clean Code",
  "Enterprise Integration",
  "Weep Not, Child",
  "A Grain of Wheat",
  "Petals of Blood",
  "Unbowed",
  "Design Patterns:",
  "The Bolter: Edwardian Heartbreak and High Society Scandal in Kenya",
  "The River Between",
  "Too Close to the Sun: The Audacious Life and Times of Denys Finch Hatton",
  "One Day I Will Write About This Place: A Memoir",
  "The Camel Bookmobile",
  "Say You're One of Them",
  "A Guide to the Birds of East Africa (Mr Malik #1)",
  "Dreams in a Time of War",
  "Nairobi Heat",
  "How to Be a Kenyan",
  "The In-Between World of Vikram Lall",
  "Nobody´s Children",
  "Circling the Sun",
  "Dust",
  "The Promise of Rain (From Kenya, With Love #1)",
  "The Watermelon King",
  "What Tears Us Apart",
  "The Ivory Needle",
  "Moving the Maasai: A Colonial Misadventure",
  "Out in the Midday Sun",
  "Too Close to the Sun: The Audacious Life and Times of Denys Finch Hatton",
  "One Day I Will Write About This Place: A Memoir",
  "The Camel Bookmobile",
  "Say You're One of Them",
];

export default titles;
